# Site settings
title: Tree of Life Lakeland
logo: assets/img/EtzChayim.jpg
email: etzchayim@dmcarroll.net
description: >- # this means to ignore newlines until "baseurl:"
  Development website for Etz Chayim Messianic Synagogue in Lakeland, Florida.
baseurl: "/treeoflifelakeland" # the subpath of your site, e.g. /blog
url: "https://etzchayimlakeland.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: Dan Carroll
